{% set name = "htcondor" %}
{% set version = "9_0_6" %}

package:
  # the top-level package should be called `htcondor`, but
  # because the metapackage needs to specify host dependencies
  # we have to rename the top-level package so that conda-build
  # doesn't get confused
  name: {{ name|lower }}-build
  version: {{ version|replace('_', '.') }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: 801b6b81485f5a0e5add0915ac33cbbef1c86c7668fdf123279be60d9ec9b8d1
  patches:
    # don't build daemons
    - no-daemons.patch
    # set C_PYTHONARCHLIB for python
    - python-archlib.patch
    # use RPATH, not RUNPATH
    - rpath.patch
    # set install paths
    - paths.patch
    # don't link libpython
    - python-no-libpython.patch
    # fix man directory
    - man-directory.patch
    # don't rebuild condor_utils for python bindings
    - python-link-condor_utils.patch

build:
  error_overdepending: true
  error_overlinking: true
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - perl
    - pkg-config  # [unix]
    - sphinx
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - {{ cdt('libselinux') }}  # [linux]
    - boost
    - expat
    - gct  # [linux]
    - krb5
    - libcurl
    - libuuid  # [unix]
    - libxml2
    - munge  # [linux]
    - openldap
    - openssl
    - pcre
    - scitokens-cpp >=0.5.0
    - sqlite
    - voms

outputs:
  - name: htcondor-classads
    build:
      run_exports:
        - {{ pin_subpackage("htcondor-classads", max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - pcre
      run:
        - pcre
    files:
      - include/classad
      - lib/libclassad*
      - bin/classad*
    test:
      commands:
        - classad_version
    about:
      home: http://htcondor.org/
      doc_url: https://htcondor.readthedocs.io/
      dev_url: https://github.com/htcondor/htcondor
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE-2.0.txt
      summary: HTCondor's classified advertisement language
      description: |
        Classified Advertisements (classads) are the lingua franca of
        HTCondor. They are used for describing jobs, workstations, and other
        resources. They are exchanged by HTCondor processes to schedule
        jobs. They are logged to files for statistical and debugging
        purposes. They are used to enquire about current state of the system.

        A classad is a mapping from attribute names to expressions. In the
        simplest cases, the expressions are simple constants (integer,
        floating point, or string). A classad is thus a form of property
        list. Attribute expressions can also be more complicated. There is a
        protocol for evaluating an attribute expression of a classad vis a vis
        another ad. For example, the expression "other.size > 3" in one ad
        evaluates to true if the other ad has an attribute named size and the
        value of that attribute is (or evaluates to) an integer greater than
        three. Two classads match if each ad has an attribute requirements
        that evaluates to true in the context of the other ad. Classad
        matching is used by the HTCondor central manager to determine the
        compatibility of jobs and workstations where they may be run.

  - name: libcondor_utils
    build:
      run_exports:
        - {{ pin_subpackage("libcondor_utils", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - gct  # [linux]
        - {{ pin_subpackage('htcondor-classads', exact=True) }}
        - krb5
        - libgomp  # [linux]
        - libuuid  # [linux]
        - munge  # [linux]
        - openssl
        - pcre
        - scitokens-cpp >=0.5.0
        - voms
      run:
        - gct  # [linux]
        - {{ pin_subpackage('htcondor-classads', exact=True) }}
        - krb5
        - munge  # [linux]
        - openssl
        - pcre
        - voms
    files:
      - lib/libcondor_utils*
    test:
      commands:
        - test -f ${PREFIX}/lib/libcondor_utils_{{ version }}${SHLIB_EXT}  # [unix]
    about:
      home: http://htcondor.org/
      doc_url: https://htcondor.readthedocs.io/
      dev_url: https://github.com/htcondor/htcondor
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE-2.0.txt
      summary: HTCondor utilities library
      description: Just the HTCondor libcondor_utils shared object library.

  - name: htcondor-utils
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ cdt('libselinux') }}  # [linux]
        - {{ pin_subpackage("htcondor-classads", exact=True) }}
        - {{ pin_subpackage("libcondor_utils", exact=True) }}
        - libcurl
        - libuuid  # [unix]
        - libgomp  # [linux]
        - openssl
      run:
        - {{ pin_subpackage("htcondor-classads", exact=True) }}
        - {{ pin_subpackage("libcondor_utils", exact=True) }}
        - libcurl
        - libuuid  # [unix]
        - openssl
    files:
      - bin/condor*
      - bin/*gahp
      - etc/condor/*
      - etc/init.d/condor*
      - etc/examples/condor
      - etc/conda/*activate.d/*_condor.sh
      - lib/Condor*.class
      - lib/*.jar
      - lib/libcondorapi*
      - lib/libchirp*
      - libexec/condor/*
      - man/man1/condor*.1
    test:
      commands:
        # check executables
        - condor_q --help
        - condor_qedit --help
        - condor_status --help
        - condor_submit --help
        - condor_submit_dag --help
        # check that the local config is used by default
        - test $(condor_config_val DAGMAN_CONDOR_SUBMIT_EXE) == "${PREFIX}/bin/condor_submit"
    about:
      home: http://htcondor.org/
      doc_url: https://htcondor.readthedocs.io/
      dev_url: https://github.com/htcondor/htcondor
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE-2.0.txt
      summary: 'HTCondor: High Throughput Computing'
      description: |
        HTCondor is a workload management system for high-throughput and
        high-performance jobs. Like other full-featured batch systems, HTCondor
        provides a job queuing mechanism, scheduling policy, priority scheme,
        resource monitoring, and resource management. Users submit their
        serial or parallel jobs to HTCondor, HTCondor places them into a queue,
        chooses when and where to run the jobs based upon a policy, carefully
        monitors their progress, and ultimately informs the user upon
        completion.

  - name: python-htcondor
    script: install-python.sh
    build:
      ignore_run_exports:
        - gct  # [linux]
        - libuuid
        - pcre
        - python
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - pkg-config  # [unix]
      host:
        - boost
        - gct  # [linux]
        - {{ pin_subpackage('libcondor_utils', exact=True) }}
        - {{ pin_subpackage('htcondor-classads', exact=True) }}
        - libuuid  # [unix]
        - munge  # [linux]
        - pcre
        - python
        - setuptools
      run:
        - {{ pin_compatible('boost') }}
        - {{ pin_subpackage('libcondor_utils', exact=True) }}
        - {{ pin_subpackage('htcondor-classads', exact=True) }}
        - python
    test:
      imports:
        - htcondor
        - classad
      requires:
        - pip
      commands:
        # check that the pip recognises that package is already installed
        # mainly by asking pip to install it again, and making sure it doesn't
        # do anything
        - python -m pip install --no-deps --index-url nothing {{ name }}
    about:
      home: http://htcondor.org/
      doc_url: https://htcondor.readthedocs.io/
      dev_url: https://github.com/htcondor/htcondor
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE-2.0.txt
      summary: Python bindings for HTCondor
      description: |
        The HTCondor Python bindings aim to expose a high-quality,
        Pythonic interface to the HTCondor client libraries. They utilize
        the same C++ libraries as HTCondor itself, meaning they have
        nearly the same behavior as the command line tools.

  - name: htcondor
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('htcondor-classads', exact=True) }}
        - {{ pin_subpackage('libcondor_utils', exact=True) }}
        - python
        - {{ pin_subpackage('python-htcondor', exact=True) }}
        - {{ pin_subpackage('htcondor-utils', exact=True) }}
    test:
      imports:
        - htcondor
        - classad
      commands:
        - condor_q --version

about:
  home: http://htcondor.org/
  doc_url: https://htcondor.readthedocs.io/
  dev_url: https://github.com/htcondor/htcondor
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE-2.0.txt
  summary: 'HTCondor: High Throughput Computing'
  description: |
    HTCondor is a workload management system for high-throughput and
    high-performance jobs. Like other full-featured batch systems, HTCondor
    provides a job queuing mechanism, scheduling policy, priority scheme,
    resource monitoring, and resource management. Users submit their
    serial or parallel jobs to HTCondor, HTCondor places them into a queue,
    chooses when and where to run the jobs based upon a policy, carefully
    monitors their progress, and ultimately informs the user upon
    completion.

extra:
  feedstock-name: htcondor
  recipe-maintainers:
    - duncanmmacleod
    - jasoncpatton
